#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#

if ! grep  --only-matching amulet <<< $I &> /dev/null; then
    cat << EOF
Našiel si smaragdový **amulet**!"

Ak chceš zbierať poklady, musíš mať premennú (variable), do ktorej budeš ukladať inventár.

Vytvor premennú (variable) a pridaj si do nej svoj poklad, takto:

export I=amulet,\$I

Svoje bohatstvo môžeš kedykoľvek skontrolovať pomocou tohto príkazu:

echo \$I

EOF
    mv ../.kaplnka ../kaplnka 2>/dev/null
    mv ../.trezor ../trezor 2>/dev/null
    mv ../.šrot ../šrot 2>/dev/null
else
    echo "Tento poklad už bol odobratý."
fi


















































































































































































































































































# Hmm, that didn't work.
# Try moving into the armoury, maybe you
# can come back to this treasure later!


