#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#
if [[ -e elixír ]]; then
    cat << EOF
Z diaľky si privolal elixír. Rýchlo ho vypiješ
a cítiš nával sily.

Pridaj si 5 HP k svojmu skóre.

EOF
else
    cat << EOF
Stránka z druidovho zväzku zaklínadiel leží na
zemi. Prezradí ti, ako privolať liečivý elixír:

# Ak chceš nájsť súbor vo tvojom systéme, použi príkaz `find`. Pre
# príklad na vyhľadávanie v tejto miestnosti:

find . -name "elixír"

# Keď nájdeš elixír, skopíruj ho do tohto adresára a
# znova spusti tento kúzelný skript.

V tejto miestnosti nie sú žiadne elixíry. Ale skús začať hľadať
pri vchode.

Tip: Použi `pwd` na určenie počtu miestností (priečinkov).
medzi tebou a vchodom.

EOF

fi


















































































































































































































































































# Hmm, toto nefungovalo.
# Pamätaj, že keď súbory končia na *
# to znamená, že sú to aplikácie.
# Skús toto:
#
# ./kúzlo

