#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#
gameover () {
    cat << EOF > corpse
Na podlahe vidíš mŕtvolu zabitého dobrodruha
zo žalára. Na mŕtvole nájdeš nasledujúce predmety:

$I

EOF
    curr=`basename $PWD`
    while [ "$curr" != "vchod" ]; do
        pushd .. &> /dev/null
        dirs -c
        curr=`basename $PWD`
    done
    unset I
    unset HP
    $SHELL
}
roll() {
    printf "Zadaj číslo:  "
    read NUM
    ALPHA=$RANDOM
    OMEGA=$RANDOM
    A=`echo $ALPHA | cut -b 1-2`
    O=`echo $OMEGA | cut -b 1-2`
    let "NUM=$ALPHA % $OMEGA"
    MONSTER=$RANDOM
    MONSTER=`echo $MONSTER | cut -b 1-2`
    NUM=`echo $NUM | cut -b 1-2`

    echo "Netvor sa zvalil " $MONSTER
    echo "Ty si sa zvalil " $NUM
    
    if [ -e ../../../.požehnanie ]; then
	let "NUM=NUM+2"
	echo "+2 bonus od tajomného zimného patróna!"
    fi
}

resolve() {
    if [[ $MONSTER -eq $NUM ]]; then
        cat << EOF
Vyhneš sa útoku, no v dôsledku toho míňaš svoj cieľ.
Roztoč to znova...

EOF
	    roll
    fi
    
    if [[ $MONSTER -lt $NUM ]]; then
        cat << EOF
Úder! Citeľný úder! Zabili ste ducha
zlého čarodejníka.

EOF
        cat << EOF > poklad
#!/bin/bash
if ! grep  --quiet --only-matching smaragd <<< \$I; then
    cat << eof
Našli ste *smaragd*! Pridaj ho do svojho inventára.

eof
else
    cat << eof
Tento poklad už bol odobratý.

eof
fi
EOF
       chmod +x poklad
       cat << EOF > platina
#!/bin/bash
if ! grep  --quiet --only-matching platina <<< \$I; then
    cat << eof
Našiel si vrece plné *platinových* mincí! Pridaj ho do
tvojho inventára.

eof
else
    cat << eof
Tento poklad už bol odobratý.

eof

fi
EOF
        chmod +x platina
    else
        cat << EOF
Tvoj meč sa neškodne hojdá vzduchom. Berieš 5
bodové poškodenie. Odpočítaj ho z tvojej premennej HP:

let HP=HP-5

EOF
        let HP=HP-5
        if [ "$HP" -le 0 ]; then
            cat << EOF
Zrazu cítiš chlad, životná sila uniká z tvojho
tela. Bol si zabitý duchom zlého čarodejníka.

KONIEC HRY!

EOF
            gameover
            exit 1
        fi
	    roll
        resolve
    fi
}

cat << EOF
Miestnosť sa trasie, z ničoho nič ťa oháňa poryv vetra.
Cítiš, že do miestnosti vstúpila prítomnosť. Bolesť, ktorú
zrazu cítiš, ťa uisťuje, že si pod útokom
strašidelnej veci!

Ak máš meč, môžeš zaútočiť. V opačnom prípade by si mal
bežať.

EOF
printf "Chcete zaútočiť? a/n  "
read RESP

if [ "$RESP" = "a" -o "$RESP" = "A" ];then
    roll
    resolve
else
    cat << EOF
Múdro sa otočíš a utečieš. Rýchlo `cd` do predchádzajúceho
adresára.

EOF
fi


















































































































































































































































































# Hmm, toto nefungovalo.
# Pamätaj, že keď súbory končia na *
# to znamená, že sú to aplikácie.
# Skús toto:
#
# ./duch

