#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#
cat << EOF
Runy, jazyk starovekých mystikov, ktorí kedysi vládli
tejto krajine, sú napísané na západnej stene.

EOF
printf "Chceš si ich prečítať? a/n "
read RESP

if [ "$RESP" = "a" -o "$RESP" = "A" ]; then
    cat << EOF
Spomínaš si na lekcie Krakena.snv, ktorý ťa učil
tieto staré písmená.

Runy sú inštrukcie, ako vyvolať portál, ktorý
ťi umožní prejsť cez neviditeľné dvere obsiahnuté
v stene.

V Bash je symbolický odkaz (symlink) *skratkou* na
iný súbor alebo adresár. Vytvor jeden odkaz z tejto miestnosti do
susednej:

ln -fs ../../../kaplnka/dvor/voliéra/hala portál

EOF
else
    cat << EOF
Rozhodneš sa, že pravdepodobne bude najlepšie opustiť magické
nápisy také, aké sú..

EOF

fi



























































































































































































































































































































# Hmm, toto nefungovalo.
# Pamätaj, že keď súbory končia na *
# to znamená, že sú to aplikácie.
# Skúste toto:
#
# ./kúzlo

