#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#
if [ -e bubon ]; then
    cat << EOF
Vojnové bubny búšia v diaľke a dávajú Nyarlathotepovi
silu.

If you know a spell to un-summon the drums, Nyarlathotep
would probably weaken!  Look up the "mv" or "rm" command.
Ak poznáš kúzlo na odvolanie bubnov, Nyarlathotepa
by to pravdepodobne oslabilo! Vyhľadaj príkaz `mv` alebo `rm`.

EOF
else
    cat << EOF
Bubnovanie prestalo. Teraz máš šancu zaútočiť!

EOF
fi


















































































































































































































































































# Hmm, that didn't work.
#
# Remember, when files end in a * 
# it means they are applications.
# Try this:
#
# ./drummer
#
# If you're not seeing the * after
# this file name, you're probably
# forgetting to use ls -F 

