#!/bin/bash
#
# Ak toto čítaš, zatúlal si sa za hranice
# a čítaš kód, ktorý riadi hru.
#
# Gratulujem!
#
# Učenie sa Linuxu je o zvedavosti, takže si prečítaj tento kód a uvidíš
# či vieš prísť na to, čo to robí.
#
# Keď si pripravený pokračovať v hre, drž sa
# zvitkov. Ak si uviazol, prejdi na Gitlab a vytvor problém (`Issue`).
# Rád ti poskytnem nápovedu.
#
if [ -e čarodejnícke-svetlo ]; then
    cat << EOF
Staroveký čarodejník, Kraken.snv, nadobúda formu pred
tvojimi oči. Oslobodil si ho a teraz bojuje po
tvojom boku proti plaziacemu sa chaosu!

EOF
else
    cat << EOF
Cítiš prítomnosť. Pravdepodobne je to len tvoja predstavivosť.

EOF
fi


















































































































































































































































































# Hmm, toto nefungovalo.
#
# Pamätaj, že keď súbory končia na *
# to znamená, že sú to aplikácie.
# Skús toto:
#
# ./čarodejnícke-svetlo
#
# Ak nevidíš * za
# týmto názvom súboru pravdepodobne si
# zabudol použiť ls -F

